services:
  # ----------------------------------
  # 1. PostgreSQL Database Service
  # ----------------------------------
  db:
    image: postgres:18-alpine
    container_name: batalha_db
    restart: unless-stopped
    
    # Load credentials from the .env file
    env_file:
      - .env
      
    # Map the internal port 5432 (default for Postgres) to external port 5432
    ports:
      - "5432:5432"
      
    # Persist the database data outside the container
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - psql_data:/var/lib/postgresql/data
      
    # Health check to ensure the DB is ready before the app starts
    healthcheck:
      test: >
        pg_isready
        -h localhost
        -U ${POSTGRES_USER}
        -d ${POSTGRES_DB}
        -p 5432
      interval: 5s
      timeout: 5s
      retries: 5


  # ----------------------------------
  # 2. Redis Cache/Broker Service
  # ---------------------------------
  redis:
    image: redis:8.2-alpine
    container_name: batalha_redis
    restart: unless-stopped
    
    env_file:
      - .env
      
    ports:
      - "6379:6379"
      
    volumes:
      - redis_data:/data
      
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 1s
      timeout: 3s
      retries: 5

  # ----------------------------------
  # 3. Your Python Application Service
  # ----------------------------------
  app:
    # Use the Dockerfile in the current directory
    build: 
      context: .
    container_name: batalha_app
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
        
    ports:
      - "8000:8000"

# Define volumes for persistent storage
volumes:
  psql_data:
  redis_data:
