name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --no-root --with dev
    - name: Run Flake8 (Style and Simple Code Quality)
      run: |
        # Checks for PEP 8 compliance and simple complexity issues.
        flake8 $$(git ls-files '*.py')

    - name: Run MyPy (Static Type Checking)
      run: |
        # Checks for type consistency based on your type hints.
        # Assuming your main source code is in a 'src' directory. Adjust if needed.
        mypy src
